apiVersion: v1
kind: PersistentVolume
metadata:
  name: datacube
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: datacube
