apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv
spec:
  storageClassName: manual
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 100Gi
  volumeName: "datacube"
