proxy:
    secretToken: "bdf362c92ab6606543b8f49bf94d1790afedeca83185b606ff8fc287d381d320"
    service:
        loadBalancerIP: "35.242.224.118"
    https:
        hosts:
            - jupyterhub-gcp-dzelge.earthsystemdatalab.net
        letsencrypt:
            contactEmail: "helge.dzierzon@brockmann-consult.de"
singleuser:
    initContainers:
        - name: esdl-shared
          image: alpine/git
          command: ["/bin/sh","-c"]
          args: ["git clone https://github.com/esa-esdl/esdl-shared.git /shared-nb"]
          securityContext:
              readOnlyRootFilesystem: true
          volumeMounts:
              - name: shared-nb
                mountPath: /shared-nb
    securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1000
        fsGroup: 100
    image:
        name: quay.io/esdc/singleuser-r-nb
        tag: "0.5.2"
        defaultUrl: "/lab"
    storage:
        homeMountPath: /home/jovyan/work/workspace
        extraVolumes:
            - name: nfs
              persistentVolumeClaim:
                  claimName: nfs
            - name: shared-nb
              emptyDir: {}
        extraVolumeMounts:
            - name: nfs
              mountPath: /home/jovyan/work/datacube
              subPath: datacube
            - name: shared-nb
              mountPath: /home/jovyan/work/shared-nb
              subPath: notebooks
    memory:
        limit: 4G
        guarantee: 2G
hub: 
    extraEnv: 
        JUPYTER_ENABLE_LAB: 1
    extraConfig: 
        c.KubeSpawner.cmd = ['jupyter-labhub']
auth:
    admin:
        users:
            - dzelge
            - admin-user
    type: github
    github: 
        clientId: "f53dd4d4fcd60da0c05f"
        clientSecret: "0280a71ffd3e7e64c280376bcc1a9020abbdcb61"
        callbackUrl: "https://jupyterhub-gcp-dzelge.earthsystemdatalab.net/hub/oauth_callback"
    whitelist:
        users:
            - dzelge
prePuller:
    continuous:
        enabled: true
cull:
    timeout: 900
    every: 300
scheduling:
    userScheduler:
        enabled: true
    userPlaceholder:
        enabled: true
        replicas: 3
    podPriority:
        enabled: true
    userPods:
        nodeAffinity:
            matchNodePurpose: require
